services:
  app:
    build: .
    image: ghcr.io/gihot-intern/game-server:0.1.5
    ports:
      - "8080:8080" # Spring HTTP server
      - "8386:8386" # WebSocket server
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
      

  redis:
    image: redis:7
    ports:
      - "6379:6379"