package com.server.game.mapper;

import org.mapstruct.Mapping;

import com.server.game._dto.request.CreateUserRequest;
import com.server.game._dto.response.CreateUserResponse;
import com.server.game._dto.response.GetUserResponse;
import com.server.game.model.User;

import org.mapstruct.Mapper;

@Mapper(componentModel = "spring")
public interface UserMapper { 
    // Id is automatically generated by MongoDB, so we ignore it in the mapping
    @Mapping(target = "id", ignore = true)
    // Password is assigned by service logic, after hashing
    @Mapping(target = "password", ignore = true)
    User toUser(CreateUserRequest createUserRequest);
    GetUserResponse toGetUserResponse(User user);
    CreateUserResponse toCreateUserResponse(User user);
}