package com.server.game.mapper;

import org.mapstruct.Mapping;

import com.server.game.dto.request.CreateUserRequest;
import com.server.game.dto.request.RegisterRequest;
import com.server.game.dto.response.CreateUserResponse;
import com.server.game.dto.response.GetUserResponse;
import com.server.game.dto.response.RegisterResponse;
import com.server.game.model.User;

import org.mapstruct.Mapper;

@Mapper(componentModel = "spring")
public interface UserMapper { 
    // Id is automatically generated by MongoDB, so we ignore it in the mapping
    @Mapping(target = "id", ignore = true)
    // Password is assigned by service logic, after hashing
    @Mapping(target = "password", ignore = true)
    // Role is set to USER by default for registration
    @Mapping(target = "role", ignore = true)
    User toUser(CreateUserRequest createUserRequest);
    
    // Id is automatically generated by MongoDB, so we ignore it in the mapping
    @Mapping(target = "id", ignore = true)
    // Password is assigned by service logic, after hashing
    @Mapping(target = "password", ignore = true)
    // Role is set to USER by default for registration
    @Mapping(target = "role", ignore = true)
    User toUser(RegisterRequest registerRequest);
    
    GetUserResponse toGetUserResponse(User user);
    CreateUserResponse toCreateUserResponse(User user);
    RegisterResponse toRegisterResponse(User user);
}